// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image9":
            case "color7":return img`
c c c c c 
c c c c c 
c c c c c 
c c c c c 
c c c c c 
`;
            case "image10":
            case "none":return img`
. . . . . 
. . . . . 
. . . . . 
. . . . . 
. . . . . 
`;
            case "image1":
            case "color0":return img`
9 9 9 9 9 
9 . . . 9 
9 . 9 9 9 
9 . 9 9 9 
9 9 9 9 9 
`;
            case "image2":
            case "color1":return img`
8 8 8 8 8 
8 . . . 8 
8 . 8 8 8 
8 . 8 8 8 
8 8 8 8 8 
`;
            case "image3":
            case "color2":return img`
4 4 4 4 4 
4 . . . 4 
4 . 4 4 4 
4 . 4 4 4 
4 4 4 4 4 
`;
            case "image4":
            case "color3":return img`
5 5 5 5 5 
5 . . . 5 
5 . 5 5 5 
5 . 5 5 5 
5 5 5 5 5 
`;
            case "image5":
            case "color4":return img`
7 7 7 7 7 
7 . . . 7 
7 . 7 7 7 
7 . 7 7 7 
7 7 7 7 7 
`;
            case "image6":
            case "color5":return img`
a a a a a 
a . . . a 
a . a a a 
a . a a a 
a a a a a 
`;
            case "image7":
            case "color6":return img`
2 2 2 2 2 
2 . . . 2 
2 . 2 2 2 
2 . 2 2 2 
2 2 2 2 2 
`;
            case "image8":
            case "game":return img`
fffffffffffffffffffffffffffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffbfffbfbbbbbfbfffbfbbbbbfffffffffff
fffffffffffffff222222222222222fffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffbbffbfbffffffbfbffffbfffffffffffff
fffffffffffffff222222222222222ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfbfbfbbbbffffbfffffbfffffffffffff
fffffffffffffff222222222222222fffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffbffbbfbffffffbfbffffbfffffffffffff
ffffffffffffffffffff22222ffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffbfffbfbbbbbfbfffbfffbfffffffffffff
ffffffffffffffffffff22222fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff22222ffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff22222ffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff22222fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff22222ffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff22222ffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff22222fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff22222ffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff22222ffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff22222fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff22222ffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff444444444444444fffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff444444444444444ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff444444444444444fffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff44444fffffffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff44444ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff44444fffffffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff44444444444444ffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff44444444444444fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff44444444444444ffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff44444fffffffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff44444ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff44444fffffffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffbfffbffbbbffbfffffbbbbffffffffffff
fffffffffffffff444444444444444fffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffbfffbfbfffbfbfffffbfffbfffffffffff
fffffffffffffff444444444444444ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbfbfffbfbfffffbfffbfffffffffff
fffffffffffffff444444444444444fffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffbfffbfbfffbfbfffffbfffbfffffffffff
fffffffffffffffffffffffffffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffbfffbffbbbffbbbbbfbbbbffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff555555555555555fffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff555555555555555ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff555555555555555fffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff55555ffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff55555fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff55555ffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff55555ffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff55555fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff55555ffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff55555ffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff55555fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff55555ffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff55555ffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff55555fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff55555ffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff777777777777ffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff77777777777777fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff77777777777777ffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff77777ffffff7777fffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff77777fffffff777ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff77777ffffff7777fffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccffffffffbfffffbbbbbfbfffbfbbbbbfbffffffffffff
fffffffffffffff77777777777777ffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccffffffffbfffffbfffffbfffbfbfffffbffffffffffff
fffffffffffffff77777777777777ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffbbbbffbfffbfbbbbffbffffffffffff
fffffffffffffff777777777777ffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcffffffffbfffffbffffffbfbffbfffffbffffffffffff
fffffffffffffff77777fff77777fffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcffffffffbbbbbfbbbbbfffbfffbbbbbfbbbbbffffffff
fffffffffffffff77777ffff77777fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff77777fffff77777fffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff77777ffffff7777fffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff77777ffffff7777ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff77777ffffff7777fffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff88888ffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff88888fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff88888ffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff88888ffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff88888fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff88888ffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff88888ffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff88888fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff88888ffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff88888ffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff88888fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff88888ffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffbbbbffbbbbffbbbffbbbbffbbbbbffffffff
ffffffffffffffffffff88888ffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccffffffffbfffffbfffffbfffbfbfffbfbffffffffffff
ffffffffffffffffffff88888fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffbfffffbfffbfbbbbffbbbbfffffffff
ffffffffffffffffffff88888ffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcffffffffffffbfbfffffbfffbfbffbffbffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcffffffffbbbbfffbbbbffbbbffbfffbfbbbbbffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffaaaaaaaaaaaafffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffaaaaaaaaaaaaaaffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffaaaaaaaaaaaaaafffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffaaaaafffffffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffaaaafffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffaaaaafffffffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffaaaaaaaaaaaffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffaaaaaaaaaaaaafffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffaaaaaaaaaaaffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffaaaaaafffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffaaaaaffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffaaaaaafffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffaaaaaaaaaaaaaaffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffaaaaaaaaaaaaaafffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffaaaaaaaaaaaaffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffcccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfcfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
