// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image10":
            case "none":return img`
. . . . . 
. . . . . 
. . b . . 
. . . . . 
. . . . . 
`;
            case "image4":
            case "color3":return img`
5 5 5 5 5 
5 1 1 5 5 
5 1 5 5 5 
5 5 5 5 5 
5 5 5 5 5 
`;
            case "image1":
            case "color0":return img`
d d d d d 
d 1 1 d d 
d 1 d d d 
d d d d d 
d d d d d 
`;
            case "image6":
            case "color5":return img`
a a a a a 
a 1 1 a a 
a 1 a a a 
a a a a a 
a a a a a 
`;
            case "image7":
            case "color6":return img`
2 2 2 2 2 
2 1 1 2 2 
2 1 2 2 2 
2 2 2 2 2 
2 2 2 2 2 
`;
            case "image8":
            case "game":return img`
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffbbbbbbbbbbbbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
fffffff222222222222222fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
fffffff222222222222222fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
fffffff222222222222222fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbfbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbfbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
fffffff444444444444444fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
fffffff444444444444444fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbbbbbbbbbbbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffff
fffffff444444444444444fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffffbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffff
fffffff44444fffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff44444fffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff44444fffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff44444444444444ffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff44444444444444ffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff44444444444444ffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff44444fffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff44444fffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff44444fffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff444444444444444fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff444444444444444fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff444444444444444fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff555555555555555fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff555555555555555fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff555555555555555fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffff1111fff1111fff1111ff11111ff11111ffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11ff11f11ff11f11ff11f11fffffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11fffff11fffff11ff11f11ff11f11fffffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffff1111ff11fffff11ff11f11ff11f1111fffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffffff11f11fffff11ff11f11111ff11fffffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11ff11f11ff11f11ff11f11fffffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffff1111fff1111fff1111ff11ff11f11111ffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbfbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffff777777777777ffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffff77777777777777ffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffff77777777777777ffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffff77777ffffff7777fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffff77777fffffff777fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffff
fffffff77777ffffff7777fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff77777777777777ffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff77777777777777ffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff777777777777ffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff77777fff77777fffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff77777ffff77777ffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ffff11111f11ff11f11111f11ffffffffffffffffffffffffffffffffffffffff
fffffff77777fffff77777fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ffff11ffff11ff11f11ffff11ffffffffffffffffffffffffffffffffffffffff
fffffff77777ffffff7777fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ffff11ffff11ff11f11ffff11ffffffffffffffffffffffffffffffffffffffff
fffffff77777ffffff7777fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ffff1111ff11ff11f1111ff11ffffffffffffffffffffffffffffffffffffffff
fffffff77777ffffff7777fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ffff11ffff11ff11f11ffff11ffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ffff11fffff1111ff11ffff11ffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11111f11111fff11fff11111f11111fffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbfbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11ff1111ff11ff11ff1111fff1111fff1111ff11111ff11111ffffffffff
ffffffffffaaaaaaaaaaaafffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11f11ff11f11ff11f11ff11f11ff11f11ff11f11ff11f11fffffffffffff
ffffffffaaaaaaaaaaaaaafffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11f11fffff11ff11f11fffff11fffff11ff11f11ff11f11fffffffffffff
ffffffffaaaaaaaaaaaaaafffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff111111f11f11f111f111111ff1111ff11fffff11ff11f11ff11f1111fffffffffff
fffffffaaaaafffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11f11ff11f11ff11fffff11f11fffff11ff11f11111ff11fffffffffffff
fffffffaaaaffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11f11ff11f11ff11f11ff11f11ff11f11ff11f11ff11f11fffffffffffff
fffffffaaaaafffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11ff1111ff11ff11ff1111fff1111fff1111ff11ff11f11111ffffffffff
ffffffffaaaaaaaaaaaffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffaaaaaaaaaaaaaffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffaaaaaaaaaaaffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffaaaaaafffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffff
fffffffffffffffffaaaaafffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffffffffffffffffaaaaaafffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffaaaaaaaaaaaaaaffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffaaaaaaaaaaaaaaffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbfbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffaaaaaaaaaaaaffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffff
fffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
            case "image2":
            case "color1":return img`
8 8 8 8 8 
8 d d 8 8 
8 d 8 8 8 
8 8 8 8 8 
8 8 8 8 8 
`;
            case "image3":
            case "color2":return img`
4 4 4 4 4 
4 5 5 4 4 
4 5 4 4 4 
4 4 4 4 4 
4 4 4 4 4 
`;
            case "image5":
            case "color4":return img`
6 6 6 6 6 
6 7 7 6 6 
6 7 6 6 6 
6 6 6 6 6 
6 6 6 6 6 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
