// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image9":
            case "color7":return img`
. . . . . 
. b b b . 
. b . b . 
. b b b . 
. . . . . 
`;
            case "image10":
            case "none":return img`
. . . . . 
. . . . . 
. . b . . 
. . . . . 
. . . . . 
`;
            case "image8":
            case "game":return img`
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11111f11ff11f111111fffffffffffffffffffffffffffffffffffffffff
fffffff222222222222222fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11ffff11ff11fff11fffffffffffffffffffffffffffffffffffffffffff
fffffff222222222222222fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff111f11f11fffff1111ffff11fffffffffffffffffffffffffffffffffffffffffff
fffffff222222222222222fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff111111f1111ffff11fffff11fffffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11f111f11fffff1111ffff11fffffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11ffff11ff11fff11fffffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11111f11ff11fff11fffffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
ffffffffffff22222ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
fffffff444444444444444fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
fffffff444444444444444fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
fffffff444444444444444fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
fffffff44444fffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
fffffff44444fffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
fffffff44444fffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
fffffff44444444444444ffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
fffffff44444444444444ffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
fffffff44444444444444ffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
fffffff44444fffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
fffffff44444fffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
fffffff44444fffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
fffffff444444444444444fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
fffffff444444444444444fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
fffffff444444444444444fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff555555555555555fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff555555555555555fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff555555555555555fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffff1111fff1111fff1111ff11111ff11111ffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11ff11f11ff11f11ff11f11fffffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11fffff11fffff11ff11f11ff11f11fffffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffff1111ff11fffff11ff11f11ff11f1111fffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffffff11f11fffff11ff11f11111ff11fffffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11ff11f11ff11f11ff11f11fffffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffff1111fff1111fff1111ff11ff11f11111ffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff55555ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffff777777777777ffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffff77777777777777ffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffff77777777777777ffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffff77777ffffff7777fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffff77777fffffff777fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffff77777ffffff7777fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffff
fffffff77777777777777ffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff77777777777777ffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff777777777777ffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff77777fff77777fffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff77777ffff77777ffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff77777fffff77777fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ffff11111f11ff11f11111f11ffffffffffffffffffffffffffffffffffffffff
fffffff77777ffffff7777fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ffff11ffff11ff11f11ffff11ffffffffffffffffffffffffffffffffffffffff
fffffff77777ffffff7777fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ffff11ffff11ff11f11ffff11ffffffffffffffffffffffffffffffffffffffff
fffffff77777ffffff7777fffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ffff1111ff11ff11f1111ff11ffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ffff11ffff11ff11f11ffff11ffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ffff11fffff1111ff11ffff11ffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11111f11111fff11fff11111f11111fffffffffffffffffffffffffffffffffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff88888ffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffaaaaaaaaaaaafffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11ff1111ff11ff11ff1111fff1111fff1111ff11111ff11111ffffffffff
ffffffffaaaaaaaaaaaaaafffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11f11ff11f11ff11f11ff11f11ff11f11ff11f11ff11f11fffffffffffff
ffffffffaaaaaaaaaaaaaafffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11f11fffff11ff11f11fffff11fffff11ff11f11ff11f11fffffffffffff
fffffffaaaaafffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff111111f11f11f111f111111ff1111ff11fffff11ff11f11ff11f1111fffffffffff
fffffffaaaaffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11f11ff11f11ff11fffff11f11fffff11ff11f11111ff11fffffffffffff
fffffffaaaaafffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11f11ff11f11ff11f11ff11f11ff11f11ff11f11ff11f11fffffffffffff
ffffffffaaaaaaaaaaaffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffff11ff11f11ff1111ff11ff11ff1111fff1111fff1111ff11ff11f11111ffffffffff
ffffffffaaaaaaaaaaaaaffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffaaaaaaaaaaaffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffaaaaaafffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffaaaaafffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffff
ffffffffffffffffaaaaaafffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffaaaaaaaaaaaaaaffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffaaaaaaaaaaaaaaffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffaaaaaaaaaaaaffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffff
fffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
            case "image4":
            case "color3":return img`
5 5 5 5 5 
5 1 1 5 5 
5 1 5 5 5 
5 5 5 5 5 
5 5 5 5 5 
`;
            case "image1":
            case "color0":return img`
d d d d d 
d 1 1 d d 
d 1 d d d 
d d d d d 
d d d d d 
`;
            case "image6":
            case "color5":return img`
a a a a a 
a 1 1 a a 
a 1 a a a 
a a a a a 
a a a a a 
`;
            case "image2":
            case "color1":return img`
8 8 8 8 8 
8 1 1 8 8 
8 1 8 8 8 
8 8 8 8 8 
8 8 8 8 8 
`;
            case "image3":
            case "color2":return img`
4 4 4 4 4 
4 1 1 4 4 
4 1 4 4 4 
4 4 4 4 4 
4 4 4 4 4 
`;
            case "image5":
            case "color4":return img`
6 6 6 6 6 
6 1 1 6 6 
6 1 6 6 6 
6 6 6 6 6 
6 6 6 6 6 
`;
            case "image7":
            case "color6":return img`
2 2 2 2 2 
2 1 1 2 2 
2 1 2 2 2 
2 2 2 2 2 
2 2 2 2 2 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
